name: Python package test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests on ubuntu-latest
      if: runner.os == 'Linux'
      run: |
        export PYTHONPATH=. && pytest tests
    
    - name: Run tests on windows-latest
      if: runner.os == 'Windows'
      run: |
        set PYTHONPATH='' && pytest tests
